"""Tests for the GR4J conceptual rainfall-runoff model."""

from __future__ import annotations

import numpy as np
import pandas as pd
import pytest


def _make_forcing(n: int = 730, seed: int = 42) -> tuple[pd.Series, pd.Series]:
    """Create synthetic daily precipitation and PET series."""
    rng = np.random.default_rng(seed)
    idx = pd.date_range("2018-01-01", periods=n, freq="D")

    # Precipitation: mostly dry days with occasional storms.
    storm = rng.choice([0, 0, 0, 0, 1], size=n)
    precip = pd.Series(storm * rng.exponential(8, n), index=idx, name="precip")

    # PET: smooth seasonal cycle (higher in summer), always positive.
    t = np.arange(n) / 365.25
    pet = pd.Series(2.5 + 2.0 * np.sin(2 * np.pi * t), index=idx, name="pet")
    pet = pet.clip(lower=0.2)

    return precip, pet


class TestGR4JSimulate:
    def test_returns_result(self):
        from aquascope.models.rainfall_runoff import GR4J

        precip, pet = _make_forcing()
        model = GR4J()
        result = model.simulate(precip, pet, warmup_days=30)
        assert len(result.streamflow) == len(precip)
        assert result.streamflow.index.equals(precip.index)

    def test_streamflow_non_negative(self):
        from aquascope.models.rainfall_runoff import GR4J

        precip, pet = _make_forcing()
        model = GR4J()
        result = model.simulate(precip, pet, warmup_days=30)
        assert (result.streamflow >= 0).all()

    def test_zero_precipitation_streamflow_decays(self):
        """With no rain at all, streamflow should trend toward zero as the
        initial routing-store water is depleted (recession behaviour)."""
        from aquascope.models.rainfall_runoff import GR4J

        idx = pd.date_range("2020-01-01", periods=200, freq="D")
        precip = pd.Series(0.0, index=idx)
        pet = pd.Series(3.0, index=idx)

        model = GR4J()
        result = model.simulate(precip, pet, warmup_days=0)
        # Streamflow in the last 20 days should be lower than in the first 20.
        assert result.streamflow.iloc[-20:].mean() < result.streamflow.iloc[:20].mean()

    def test_params_property_matches_constructor(self):
        from aquascope.models.rainfall_runoff import GR4J

        model = GR4J(x1=300.0, x2=1.0, x3=80.0, x4=2.0)
        assert model.params == {"X1": 300.0, "X2": 1.0, "X3": 80.0, "X4": 2.0}

    def test_unit_hydrographs_sum_to_one(self):
        from aquascope.models.rainfall_runoff import GR4J

        model = GR4J(x4=2.5)
        uh1, uh2 = model._unit_hydrographs()
        assert uh1.sum() == pytest.approx(1.0, abs=1e-6)
        assert uh2.sum() == pytest.approx(1.0, abs=1e-6)

    def test_higher_x1_increases_storage_capacity(self):
        """A larger production store should produce a smoother, lower-peak
        hydrograph for the same forcing (more storage to absorb rainfall)."""
        from aquascope.models.rainfall_runoff import GR4J

        precip, pet = _make_forcing()
        small_store = GR4J(x1=50.0).simulate(precip, pet, warmup_days=30)
        large_store = GR4J(x1=1000.0).simulate(precip, pet, warmup_days=30)
        assert large_store.streamflow.max() <= small_store.streamflow.max()


class TestGR4JCalibrate:
    def test_calibration_recovers_known_parameters(self):
        """Generate synthetic 'observed' discharge from a known parameter
        set, then check calibration finds a comparably-skilled fit."""
        from aquascope.models.rainfall_runoff import GR4J, calibrate

        precip, pet = _make_forcing(n=800)
        true_model = GR4J(x1=400.0, x2=0.5, x3=100.0, x4=2.0)
        observed = true_model.simulate(precip, pet, warmup_days=0).streamflow

        result = calibrate(
            precip, pet, observed,
            objective="kge", warmup_days=100, maxiter=15, seed=1,
        )
        # The objective should reflect a strong fit on data generated by
        # a GR4J model of the same structure.
        assert result.objective_value > 0.8

    def test_invalid_objective_raises(self):
        from aquascope.models.rainfall_runoff import calibrate

        precip, pet = _make_forcing(n=100)
        observed = pd.Series(np.zeros(100), index=precip.index)
        with pytest.raises(ValueError, match="Unknown objective"):
            calibrate(precip, pet, observed, objective="not_a_metric", maxiter=2)

    def test_result_params_within_bounds(self):
        from aquascope.models.rainfall_runoff import GR4J_PARAM_BOUNDS, calibrate

        precip, pet = _make_forcing(n=400)
        true_model_streamflow = pd.Series(
            np.abs(np.random.default_rng(0).normal(2, 1, 400)), index=precip.index
        )
        result = calibrate(precip, pet, true_model_streamflow, maxiter=5, seed=2)
        for key, (lo, hi) in GR4J_PARAM_BOUNDS.items():
            assert lo <= result.params[key] <= hi
